services:
  - type: web
    name: auramed-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: DISABLE_REDIS
        value: "true"
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: AI_SERVICE_URL
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false

  - type: web
    name: auramed-ai-service
    env: python
    rootDir: ai-service
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    autoDeploy: true
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false

  - type: static
    name: auramed-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    plan: free
    autoDeploy: true
    envVars:
      - key: VITE_API_URL
        sync: false
